<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; The logic of hypothesis testing – Quantitative Methods I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./07-categorical-data.html" rel="next">
<link href="./05-logical-models.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7202036dd3638cbfcbeb4151d116aa42.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./06-hypothesis-testing.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The logic of hypothesis testing</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods I</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-r-and-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting started with R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-data-management-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data management I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-data-management-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data and data management II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data visualisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-logical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Thinking logically and visually about data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-hypothesis-testing.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The logic of hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-categorical-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analysing categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-comparing-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Comparing means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-factor-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factor analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-regression-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression: the basic model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-regression-presentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regression: presenting results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-regression-dummies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression: dummy variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-regression-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression: interactions and non-linear associations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#a-sample-is-not-a-population" id="toc-a-sample-is-not-a-population" class="nav-link active" data-scroll-target="#a-sample-is-not-a-population"><span class="header-section-number">6.1</span> A sample is not a population</a>
  <ul class="collapse">
  <li><a href="#what-a-random-sample-is" id="toc-what-a-random-sample-is" class="nav-link" data-scroll-target="#what-a-random-sample-is"><span class="header-section-number">6.1.1</span> What a random sample is</a></li>
  </ul></li>
  <li><a href="#measuring-variation" id="toc-measuring-variation" class="nav-link" data-scroll-target="#measuring-variation"><span class="header-section-number">6.2</span> Measuring variation</a>
  <ul class="collapse">
  <li><a href="#why-n---1" id="toc-why-n---1" class="nav-link" data-scroll-target="#why-n---1"><span class="header-section-number">6.2.1</span> Why <span class="math inline">\(n - 1\)</span></a></li>
  </ul></li>
  <li><a href="#sec-repeated" id="toc-sec-repeated" class="nav-link" data-scroll-target="#sec-repeated"><span class="header-section-number">6.3</span> What happens when you sample repeatedly</a>
  <ul class="collapse">
  <li><a href="#the-point-of-all-that" id="toc-the-point-of-all-that" class="nav-link" data-scroll-target="#the-point-of-all-that"><span class="header-section-number">6.3.1</span> The point of all that</a></li>
  </ul></li>
  <li><a href="#sec-95" id="toc-sec-95" class="nav-link" data-scroll-target="#sec-95"><span class="header-section-number">6.4</span> The 95% rule</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals"><span class="header-section-number">6.5</span> Confidence intervals</a></li>
  <li><a href="#hypothesis-tests" id="toc-hypothesis-tests" class="nav-link" data-scroll-target="#hypothesis-tests"><span class="header-section-number">6.6</span> Hypothesis tests</a>
  <ul class="collapse">
  <li><a href="#a-null-hypothesis-worth-testing" id="toc-a-null-hypothesis-worth-testing" class="nav-link" data-scroll-target="#a-null-hypothesis-worth-testing"><span class="header-section-number">6.6.1</span> A null hypothesis worth testing</a></li>
  <li><a href="#step-1-how-far-is-the-sample-from-the-null" id="toc-step-1-how-far-is-the-sample-from-the-null" class="nav-link" data-scroll-target="#step-1-how-far-is-the-sample-from-the-null"><span class="header-section-number">6.6.2</span> Step 1: how far is the sample from the null?</a></li>
  <li><a href="#step-2-measure-the-distance-in-standard-errors" id="toc-step-2-measure-the-distance-in-standard-errors" class="nav-link" data-scroll-target="#step-2-measure-the-distance-in-standard-errors"><span class="header-section-number">6.6.3</span> Step 2: measure the distance in standard errors</a></li>
  <li><a href="#step-3-where-does-that-land-if-the-null-is-true" id="toc-step-3-where-does-that-land-if-the-null-is-true" class="nav-link" data-scroll-target="#step-3-where-does-that-land-if-the-null-is-true"><span class="header-section-number">6.6.4</span> Step 3: where does that land if the null is true?</a></li>
  <li><a href="#step-4-from-a-location-to-a-probability" id="toc-step-4-from-a-location-to-a-probability" class="nav-link" data-scroll-target="#step-4-from-a-location-to-a-probability"><span class="header-section-number">6.6.5</span> Step 4: from a location to a probability</a></li>
  <li><a href="#the-same-distance-different-evidence" id="toc-the-same-distance-different-evidence" class="nav-link" data-scroll-target="#the-same-distance-different-evidence"><span class="header-section-number">6.6.6</span> The same distance, different evidence</a></li>
  <li><a href="#the-rule-of-1.96-again" id="toc-the-rule-of-1.96-again" class="nav-link" data-scroll-target="#the-rule-of-1.96-again"><span class="header-section-number">6.6.7</span> The rule of 1.96, again</a></li>
  <li><a href="#a-test-is-only-as-interesting-as-its-null" id="toc-a-test-is-only-as-interesting-as-its-null" class="nav-link" data-scroll-target="#a-test-is-only-as-interesting-as-its-null"><span class="header-section-number">6.6.8</span> A test is only as interesting as its null</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The logic of hypothesis testing</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Everything up to now has described the data in front of us. From here on we want to say something about the world the data came from — and that is a different and much harder claim.</p>
<p>This chapter has no new method in it. It is the reasoning that every method in the rest of the course depends on, and it is worth slowing down for, because almost every mistake people make with statistics is a mistake about this rather than about arithmetic.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>swe <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/swe.rds"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>turnout <span class="ot">&lt;-</span> readr<span class="sc">::</span><span class="fu">read_csv</span>(<span class="st">"data/turnout.csv"</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="a-sample-is-not-a-population" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="a-sample-is-not-a-population"><span class="header-section-number">6.1</span> A sample is not a population</h2>
<p>The <strong>population</strong> is the group you want to know about: everyone entitled to vote in Sweden in 2022. The <strong>sample</strong> is the 2845 people who actually answered.</p>
<p>You want to talk about the first and you only have the second. Everything in this chapter is about what that costs.</p>
<p>Start with something we can check, because we know the right answer. Our survey reports how many people voted. So does the electoral authority.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>turnout <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(study <span class="sc">==</span> <span class="st">"SWE_2022"</span>) <span class="sc">|&gt;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(country, n, reported, official, gap)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 1 × 5
##   country     n reported official   gap
##   &lt;chr&gt;   &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt;
## 1 Sweden   2687     97.3     84.2  13.1</code></pre>
</div>
</div>
<p>97.3% against 84.2%. The survey is out by 13.1 percentage points.</p>
<p>Now the important part. That could be bad luck — this particular sample happening to catch more voters than average. If so, another study would miss in the other direction. CSES Module 6 contains 18 election studies in 17 countries, run by different organisations using different methods, so we can look.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>turnout <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">paste</span>(country, year),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">label =</span> <span class="fu">reorder</span>(label, gap)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gap, <span class="at">y =</span> label)) <span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Reported turnout minus official turnout (percentage points)"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="cn">NULL</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-turnout" class="quarto-float quarto-figure quarto-figure-center anchored" width="1050">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-turnout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-hypothesis-testing_files/figure-html/fig-turnout-1.png" id="fig-turnout" class="img-fluid figure-img" width="1050">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-turnout-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1
</figcaption>
</figure>
</div>
</div>
</div>
<p><code>geom_col()</code> draws bars whose length is a value in the data, as against <code>geom_bar()</code>, which counts rows. Each bar is one study, labelled with <code>paste()</code> as country and year: Portugal has two, and labelled by country alone its two bars would be stacked into one, as long as both gaps added together. <code>reorder()</code> sorts one variable by another, so the studies come out in order of the size of the gap rather than alphabetically. <code>geom_vline()</code> draws a vertical line, with <code>xintercept</code> saying where on the horizontal axis it sits. <code>y = NULL</code> removes the axis title, because “label” over a list of countries and years carries nothing.</p>
<p>Every single one is positive.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>turnout <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">studies =</span> <span class="fu">n</span>(),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">over_reporting =</span> <span class="fu">sum</span>(gap <span class="sc">&gt;</span> <span class="dv">0</span>),</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">smallest =</span> <span class="fu">min</span>(gap),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">largest =</span> <span class="fu">max</span>(gap)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 1 × 4
##   studies over_reporting smallest largest
##     &lt;int&gt;          &lt;int&gt;    &lt;dbl&gt;   &lt;dbl&gt;
## 1      18             18      5.2    30.5</code></pre>
</div>
</div>
<p>Eighteen studies, eighteen over-reports, from 5.2 to 30.5 percentage points. Nothing that goes the same way eighteen times out of eighteen is bad luck.</p>
<p>This is the distinction the whole chapter turns on.</p>
<p><strong>Random error</strong> is the sample missing the population by chance. It is unavoidable, it goes both ways, it shrinks as the sample grows, and — this is the useful part — <strong>it can be measured</strong>. Most of this chapter is about measuring it.</p>
<p><strong>Systematic error</strong> is the sample missing the population in a consistent direction. Here, people who do not vote are less likely to answer a survey about an election, and some of those who do answer say they voted when they did not. It does not go both ways, <strong>it does not shrink as the sample grows</strong>, and no statistical method in this course will detect it or fix it.</p>
<blockquote class="blockquote">
<p>A bigger sample buys you less random error and nothing whatever against systematic error. A survey of ten million people, all of them recruited in the same biased way, is wrong by exactly as much as a survey of a thousand — it is just more confident about it.</p>
</blockquote>
<section id="what-a-random-sample-is" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="what-a-random-sample-is"><span class="header-section-number">6.1.1</span> What a random sample is</h3>
<p>The methods in the rest of this course all assume a <strong>random sample</strong>: every member of the population has a known, non-zero chance of being selected.</p>
<p>The Swedish study comes close. Statistics Sweden drew names from the population register, which is about as good as sampling gets. What it could not control was who answered — and that is where the turnout gap comes from. A perfect sampling frame does not save you if response is selective.</p>
<div class="discussion">
<p><strong>A question.</strong> The survey also reports 14.4% voting for the Sweden Democrats, where the official result recorded by the Swedish electoral authority was 20.5%.</p>
<p>Is that the same problem as the turnout gap, or a different one? Which of the two would a larger sample help with?</p>
</div>
<blockquote class="blockquote">
<p>When your cases are countries rather than people, you never have a random sample — there is only one world and you have all of it, or the part of it that publishes data. Social scientists routinely run these methods on country data anyway and treat the result as if the assumption held. You should know that this is what is happening.</p>
</blockquote>
</section>
</section>
<section id="measuring-variation" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="measuring-variation"><span class="header-section-number">6.2</span> Measuring variation</h2>
<p>To measure random error we first need to measure spread. How far apart are the values in a variable?</p>
<p>The natural starting point is how far each case sits from the mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>lr <span class="ot">&lt;-</span> swe<span class="sc">$</span>lr_self[<span class="sc">!</span><span class="fu">is.na</span>(swe<span class="sc">$</span>lr_self)]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>deviations <span class="ot">&lt;-</span> lr <span class="sc">-</span> <span class="fu">mean</span>(lr)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">sum</span>(deviations), <span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0</code></pre>
</div>
</div>
<p>Zero. Not approximately — exactly, up to rounding. That is what a mean <em>is</em>: the point where the distances above and below balance. So the sum of deviations is useless as a measure of spread; it is zero for every variable that ever existed.</p>
<p>The fix is to square the deviations first, which makes them all positive, then average them. That average is the <strong>variance</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>squared <span class="ot">&lt;-</span> deviations<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(squared) <span class="sc">/</span> (<span class="fu">length</span>(lr) <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 7.798143</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(lr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 7.798143</code></pre>
</div>
</div>
<p>Squaring solved one problem and created another: the variance is in squared units. For a 0-to-10 scale it is in “scale points squared”, which means nothing. Take the square root and you are back on the original scale. That is the <strong>standard deviation</strong>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(lr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 2.792515</code></pre>
</div>
</div>
<p>Roughly, the standard deviation is the typical distance of a case from the mean. Here it is about 2.8 points on a scale running from 0 to 10.</p>
<p>In formulas, with <span class="math inline">\(\bar{x}\)</span> for the mean and <span class="math inline">\(n\)</span> for the number of cases:</p>
<p><span class="math display">\[s^2 = \frac{\sum(x_i - \bar{x})^2}{n - 1} \qquad s = \sqrt{s^2}\]</span></p>
<section id="why-n---1" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="why-n---1"><span class="header-section-number">6.2.1</span> Why <span class="math inline">\(n - 1\)</span></h3>
<p>Notice that we divided by <code>length(lr) - 1</code> rather than by <code>length(lr)</code>, and that <code>var()</code> agreed.</p>
<p>The reason is that we are not describing these 2448 people. We are using them to estimate the spread in the population. And a sample is systematically <em>less</em> spread out than the population it came from, because the rare extreme cases are, by definition, rarely sampled.</p>
<p>So the obvious calculation would be biased downwards, every time. Dividing by <span class="math inline">\(n-1\)</span> instead of <span class="math inline">\(n\)</span> makes the result slightly larger and corrects it. With thousands of cases the difference is invisible; with twelve it matters.</p>
</section>
</section>
<section id="sec-repeated" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sec-repeated"><span class="header-section-number">6.3</span> What happens when you sample repeatedly</h2>
<p>Here is the central idea, and R lets us watch it happen rather than take it on trust.</p>
<p>Suppose our 2448 respondents were the whole population, and their mean left-right position, 5.24, were the true value. Now draw a small sample of 50 from them and take its mean.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">sample</span>(lr, <span class="at">size =</span> <span class="dv">50</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 5.3</code></pre>
</div>
</div>
<p><code>sample()</code> draws at random from a vector; <code>size</code> says how many. <code>set.seed()</code> fixes the random number generator so that you get the same “random” draw as this page did — without it your number will differ, which is the point.</p>
<p>That sample missed. Draw another and it will miss differently. The question is: <strong>by how much, typically?</strong></p>
<p>We can just do it. <code>replicate()</code> runs an expression many times and collects the results.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">2000</span>, <span class="fu">mean</span>(<span class="fu">sample</span>(lr, <span class="at">size =</span> <span class="dv">50</span>)))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(sample_means)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 2000</code></pre>
</div>
</div>
<p>Two thousand samples, two thousand means. What do they look like?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(sample_means), <span class="fu">aes</span>(<span class="at">x =</span> sample_means)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.1</span>, <span class="at">fill =</span> <span class="st">"grey60"</span>) <span class="sc">+</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">mean</span>(lr), <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Mean of a sample of 50"</span>,</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Number of samples"</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-sampling" class="quarto-float quarto-figure quarto-figure-center anchored" width="1050">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sampling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-hypothesis-testing_files/figure-html/fig-sampling-1.png" id="fig-sampling" class="img-fluid figure-img" width="1050">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-sampling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2
</figcaption>
</figure>
</div>
</div>
</div>
<p>Three things to notice, and all of them matter.</p>
<p><strong>It is centred on the truth.</strong> The vertical line — drawn by <code>geom_vline()</code> again, with <code>linewidth</code> making it thicker than the default — is the population mean. The samples scatter around it rather than drifting off somewhere else.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(sample_means)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 5.22905</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(lr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 5.23652</code></pre>
</div>
</div>
<p><strong>It is bell-shaped</strong>, even though the variable itself is not — <code>lr_self</code> is a lumpy 0-to-10 scale with a spike at 5. The distribution of <em>sample means</em> comes out smooth and symmetric anyway. This happens almost regardless of the shape of the original variable, which is the single most useful fact in statistics.</p>
<p><strong>Its spread is measurable.</strong> That is the number we actually want:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sample_means)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.4000784</code></pre>
</div>
</div>
<p>That is how far a sample of 50 typically misses by. It has a name: the <strong>standard error</strong>.</p>
<section id="the-point-of-all-that" class="level3" data-number="6.3.1">
<h3 data-number="6.3.1" class="anchored" data-anchor-id="the-point-of-all-that"><span class="header-section-number">6.3.1</span> The point of all that</h3>
<p>We simulated it because we could — we had all 2448 cases and could pretend they were a population. In real research you have one sample and no way to draw another.</p>
<p>The remarkable thing is that you do not need to. The standard error can be calculated from a single sample:</p>
<p><span class="math display">\[SE = \frac{s}{\sqrt{n}}\]</span></p>
<p>The standard deviation, divided by the square root of the sample size. Compare it with what the simulation produced:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(lr) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.3949213</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(sample_means)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.4000784</code></pre>
</div>
</div>
<p>0.395 against 0.400. The formula tells you, from one sample, what two thousand samples would have shown you.</p>
<p>Two consequences follow from the <span class="math inline">\(\sqrt{n}\)</span> on the bottom.</p>
<p><strong>More data means less random error</strong> — the standard error shrinks as the sample grows.</p>
<p><strong>But slowly.</strong> To halve the standard error you need <strong>four times</strong> the data. This is why the difference between a sample of 1,000 and a sample of 2,000 is much smaller than people expect, and why the useful question about a survey is almost never “is it big enough”.</p>
<div class="discussion">
<p><strong>A question.</strong> Our full sample has 2448 valid answers on <code>lr_self</code>, not 50.</p>
<p>Work out the standard error of the mean for the full sample. Then ask what would have to be true for that number to be a good description of how far our estimate is from the truth about Sweden — and whether the turnout table at the top of this chapter gives you any confidence that it is.</p>
</div>
</section>
</section>
<section id="sec-95" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-95"><span class="header-section-number">6.4</span> The 95% rule</h2>
<p>Because sampling distributions come out bell-shaped, one fact about the normal distribution does most of the practical work.</p>
<p>In a normal distribution, about <strong>95% of the values lie within about two standard deviations of the mean</strong>. More precisely, 1.96.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.96</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.9750021</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="fl">1.96</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.0249979</code></pre>
</div>
</div>
<p><code>pnorm()</code> gives the proportion of a normal distribution below a given number of standard deviations from the mean. Below 1.96 lies 97.5% of it; <code>lower.tail = FALSE</code> asks for the other end instead, giving the 2.5% above. Two tails of 2.5% each leaves 95% in the middle.</p>
<p>Applied to a sampling distribution, that says: about 95% of samples produce an estimate within 1.96 standard errors of the truth.</p>
</section>
<section id="confidence-intervals" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="confidence-intervals"><span class="header-section-number">6.5</span> Confidence intervals</h2>
<p>Turn that round and you have the most useful thing in this chapter.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>estimate <span class="ot">&lt;-</span> <span class="fu">mean</span>(lr)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>se <span class="ot">&lt;-</span> <span class="fu">sd</span>(lr) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="fu">length</span>(lr))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>lower <span class="ot">&lt;-</span> estimate <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> se</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>upper <span class="ot">&lt;-</span> estimate <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> se</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(estimate, lower, upper), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 5.237 5.126 5.347</code></pre>
</div>
</div>
<p>The mean is 5.24, with a 95% confidence interval from 5.13 to 5.35.</p>
<p>Read it as: <strong>a range of values for the population figure that this sample is consistent with.</strong> Values inside the interval are ones the data cannot rule out. Values outside it are ones the data argues against.</p>
<blockquote class="blockquote">
<p><strong>What a confidence interval does not mean.</strong> It is tempting to say “there is a 95% probability that the true value is in this interval”. That is the standard misstatement, and it is worth knowing why.</p>
<p>The population value is a fixed number. It is either inside this interval or it is not; there is no probability about it. The 95% describes <strong>the procedure</strong>, not this particular interval: if you drew sample after sample and built an interval each time, about 95% of those intervals would contain the true value. You never learn whether yours is one of them.</p>
<p>In practice people read a confidence interval as a range of plausible values, and that is a reasonable working habit. But when you write it up, write it as a range, not as a probability.</p>
</blockquote>
<p>And note what it is silent about. The interval says nothing about the 13.1-point turnout gap. It measures random error only. <strong>A narrow confidence interval on a biased estimate is a precise wrong answer.</strong></p>
</section>
<section id="hypothesis-tests" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="hypothesis-tests"><span class="header-section-number">6.6</span> Hypothesis tests</h2>
<p>The last piece. Most research questions are not “what is the value” but “is there anything there at all” — does this differ between groups, is this related to that.</p>
<p>Such questions get turned into a pair of hypotheses:</p>
<ul>
<li>The <strong>null hypothesis</strong>: there is nothing there. No difference, no association — the population value is the one that “nothing” would give.</li>
<li>The <strong>alternative hypothesis</strong>: there is something there. The population value is not that.</li>
</ul>
<p>A test asks one thing: <strong>how far is the sample from what the null hypothesis says, and is that further than sampling noise would carry it?</strong> The rest of this section builds that up one step at a time, using a question worth asking.</p>
<section id="a-null-hypothesis-worth-testing" class="level3" data-number="6.6.1">
<h3 data-number="6.6.1" class="anchored" data-anchor-id="a-null-hypothesis-worth-testing"><span class="header-section-number">6.6.1</span> A null hypothesis worth testing</h3>
<p>The left-right scale runs from 0 to 10, and 5 is its middle. A claim you will hear is that Swedish voters are, on average, exactly in the centre. That gives a pair of hypotheses:</p>
<ul>
<li>Null: the mean left-right position of Swedish voters is <strong>5</strong>.</li>
<li>Alternative: it is <strong>not 5</strong> — it is somewhere else, in either direction.</li>
</ul>
<p>The sample mean is 5.24, not 5. But a sample mean is never exactly the population value; <a href="#sec-repeated" class="quarto-xref"><span>Section 6.3</span></a> showed sample means scattering around the truth. The question is whether 5.24 is the kind of miss a sample makes by chance when the truth is 5.</p>
</section>
<section id="step-1-how-far-is-the-sample-from-the-null" class="level3" data-number="6.6.2">
<h3 data-number="6.6.2" class="anchored" data-anchor-id="step-1-how-far-is-the-sample-from-the-null"><span class="header-section-number">6.6.2</span> Step 1: how far is the sample from the null?</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>null_value <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>distance <span class="ot">&lt;-</span> estimate <span class="sc">-</span> null_value</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>distance</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.2365196</code></pre>
</div>
</div>
<p>The sample is 0.24 points from where the null hypothesis puts the population. On its own that number cannot answer the question. Is 0.24 points a lot? It depends on how much a sample mean moves about from sample to sample — and that is exactly what the standard error measures.</p>
</section>
<section id="step-2-measure-the-distance-in-standard-errors" class="level3" data-number="6.6.3">
<h3 data-number="6.6.3" class="anchored" data-anchor-id="step-2-measure-the-distance-in-standard-errors"><span class="header-section-number">6.6.3</span> Step 2: measure the distance in standard errors</h3>
<p>The standard error is the yardstick. <a href="#sec-repeated" class="quarto-xref"><span>Section 6.3</span></a> showed what it is: the spread of the means you would get from sample after sample. So divide the distance by it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> distance <span class="sc">/</span> se</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>z</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 4.19061</code></pre>
</div>
</div>
<p>The sample mean sits 4.19 <strong>standard errors</strong> from the null value. That is the <strong>test statistic</strong>:</p>
<p><span class="math display">\[z = \frac{\text{estimate} - \text{null value}}{\text{standard error}}\]</span></p>
<p>This is the signal-to-noise ratio from the start of the section, made concrete. The signal is the distance between what we found and what the null predicts. The noise is the standard error — how far a sample mean typically wanders by chance alone.</p>
</section>
<section id="step-3-where-does-that-land-if-the-null-is-true" class="level3" data-number="6.6.4">
<h3 data-number="6.6.4" class="anchored" data-anchor-id="step-3-where-does-that-land-if-the-null-is-true"><span class="header-section-number">6.6.4</span> Step 3: where does that land if the null is true?</h3>
<p>Now suppose the null hypothesis were true. Then the population mean would be 5, and the means of repeated samples would pile up around 5 in the bell shape you saw in <a href="#sec-repeated" class="quarto-xref"><span>Section 6.3</span></a>, with a spread of one standard error. Measured in standard errors, that is a normal distribution centred on 0.</p>
<p>The test statistic is <strong>a location in that distribution</strong>: how far out our sample sits among all the samples a world with no effect would produce.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-hypothesis-testing_files/figure-html/fig-null-1.png" class="img-fluid figure-img" width="1050">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Where sample means would fall if the null hypothesis were true. The bottom axis measures the distance from the null value in standard errors; the top axis gives the same positions as mean left-right placements, with the null value of 5 at the centre. The shaded tails are the 5% of samples furthest from it, beyond ±1.96. The vertical line is our sample.
</figcaption>
</figure>
</div>
</div>
</div>
<p>At 4.2 standard errors, our sample is past the point where the curve has practically run out. Samples that far from 5 almost never happen when the truth is 5.</p>
</section>
<section id="step-4-from-a-location-to-a-probability" class="level3" data-number="6.6.5">
<h3 data-number="6.6.5" class="anchored" data-anchor-id="step-4-from-a-location-to-a-probability"><span class="header-section-number">6.6.5</span> Step 4: from a location to a probability</h3>
<p>The <strong>p-value</strong> turns that location into a number: the share of the null distribution that lies <strong>at least as far from the null value as our sample</strong>, in either direction.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>z_size <span class="ot">&lt;-</span> <span class="fu">abs</span>(z)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>beyond <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(z_size, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> beyond</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 2.782052e-05</code></pre>
</div>
</div>
<p><code>abs()</code> gives the size of a number without its sign, because a sample 4.2 standard errors <em>below</em> 5 would be just as much evidence against the null as one 4.2 above. <code>pnorm()</code> with <code>lower.tail = FALSE</code>, from <a href="#sec-95" class="quarto-xref"><span>Section 6.4</span></a>, gives the share of the normal distribution beyond that point in one tail. The alternative was “not 5, in either direction”, so both tails count, and the share is doubled.</p>
<p>The printed <code>2.78e-05</code> is how R writes 0.0000278: the number after <code>e-</code> says how many places to move the decimal point to the left. If the average Swede really sat at exactly 5, a sample as far from it as ours would turn up about once in 36,000 samples. That is the p-value: <strong>the probability of a result at least this far from the null, if the null were true.</strong></p>
<p>So the no-effect story is a poor explanation of these data. The conventional threshold is 0.05, and this is far below it.</p>
<blockquote class="blockquote">
<p><strong>Read that definition again</strong>, because the direction catches people out. The p-value is the probability of the <em>data</em> given no effect. It is <strong>not</strong> the probability that there is no effect, and it is not the probability that you are wrong. It cannot be, because it assumes the null hypothesis to compute the number, and you cannot use an assumption as evidence about itself.</p>
</blockquote>
</section>
<section id="the-same-distance-different-evidence" class="level3" data-number="6.6.6">
<h3 data-number="6.6.6" class="anchored" data-anchor-id="the-same-distance-different-evidence"><span class="header-section-number">6.6.6</span> The same distance, different evidence</h3>
<p>Here is why the standard error matters so much. Suppose the same mean, 5.24, had come from only 100 respondents rather than 2,448. The distance from 5 is identical. The standard error is not.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>se_100 <span class="ot">&lt;-</span> <span class="fu">sd</span>(lr) <span class="sc">/</span> <span class="fu">sqrt</span>(<span class="dv">100</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>z_100 <span class="ot">&lt;-</span> distance <span class="sc">/</span> se_100</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>p_100 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(z_100), <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">c</span>(se_100, z_100, p_100), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.279 0.847 0.397</code></pre>
</div>
</div>
<p>With 100 respondents the standard error is 0.28 rather than 0.056, the same 0.24 points is only 0.85 standard errors, and the p-value is 0.40.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-null-100" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-null-100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="06-hypothesis-testing_files/figure-html/fig-null-100-1.png" class="img-fluid figure-img" width="1050">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-null-100-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.4: The same distance from 5 in a sample of 100. The top axis is wider than before because the standard error is larger. The shaded area is the p-value: the share of samples at least this far from the null, in either direction, if the null were true.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now the p-value is visible as an area: 40% of samples would land at least that far from 5 even if 5 were the truth. A sample like that is entirely ordinary in a world with no effect, so it is no evidence against the null.</p>
<p>The distance was the same both times. <strong>What changed was the standard error</strong>, and with it the location of the sample in the null distribution. That is how the size of a sample enters a test: through the square root of <em>n</em> in the standard error.</p>
</section>
<section id="the-rule-of-1.96-again" class="level3" data-number="6.6.7">
<h3 data-number="6.6.7" class="anchored" data-anchor-id="the-rule-of-1.96-again"><span class="header-section-number">6.6.7</span> The rule of 1.96, again</h3>
<p><a href="#sec-95" class="quarto-xref"><span>Section 6.4</span></a> showed that 95% of a normal distribution lies within 1.96 standard deviations of its centre. So a sample more than 1.96 standard errors from the null value lands in the outer 5% — and that is exactly when the p-value falls below 0.05.</p>
<p>It is also exactly when the 95% confidence interval leaves out the null value, because the interval is the estimate plus and minus 1.96 standard errors. Confidence intervals and p-values are two views of the same calculation. Our interval runs from 5.13 to 5.35: it does not include 5, and the p-value is below 0.05.</p>
</section>
<section id="a-test-is-only-as-interesting-as-its-null" class="level3" data-number="6.6.8">
<h3 data-number="6.6.8" class="anchored" data-anchor-id="a-test-is-only-as-interesting-as-its-null"><span class="header-section-number">6.6.8</span> A test is only as interesting as its null</h3>
<p>The null hypothesis of 5 was worth testing: it is a claim people make. Testing whether the mean differs from 0 would give an even smaller p-value and mean nothing at all, because there was never any reason to think the average Swede sits at the far left of the scale. <strong>A test is only interesting if the null hypothesis was worth entertaining.</strong> Much published research reports p-values for comparisons nobody doubted.</p>
<p>The next three sessions are all applications of this one idea. Session 7 tests whether two categorical variables are related, session 8 whether two means differ, session 9 whether two continuous variables move together. Each has its own estimate and its own standard error, and R does the steps above in one function call, but the logic is always these four steps: a distance from the null, measured in standard errors, located in the distribution the null predicts, and read off as a probability.</p>
<blockquote class="blockquote">
<p>With small samples the functions you will meet, such as <code>t.test()</code> in session 8, use the <em>t</em> distribution instead of the normal — a slightly wider bell that allows for the standard error itself being estimated from a small sample. With thousands of cases the two are indistinguishable, and <code>t.test()</code> gives the same answer as the steps above.</p>
</blockquote>
<div class="reporting">
<p><strong>How to write it up.</strong></p>
<blockquote class="blockquote">
<p>Swedish respondents place themselves close to the centre of the left-right scale (mean = 5.24, 95% CI [5.13, 5.35], <em>n</em> = 2,448), but slightly to the right of its midpoint of 5 (<em>z</em> = 4.19, <em>p</em> &lt; 0.001).</p>
</blockquote>
<p>Report the estimate, the interval, and the number of cases the estimate rests on. For a test, add the test statistic and the p-value — and say what the null value was. Mistakes to avoid:</p>
<ul>
<li><strong>Reporting a p-value without the estimate.</strong> “The difference was significant (p &lt; .05)” does not say how big it was, which is what the reader needs.</li>
<li><strong>Reporting more decimal places than the data supports.</strong> A left-right scale with eleven whole-number points does not measure anything to three decimals.</li>
<li><strong>Calling a result “significant” in prose without the word “statistically”.</strong> In ordinary English significant means important, and a statistically significant finding can be far too small to matter.</li>
<li><strong>Treating p just above 0.05 as no effect and just below as an effect.</strong> 0.049 and 0.051 are the same evidence. The threshold is a convention, not a discovery.</li>
<li><strong>Forgetting the <em>n</em></strong>, especially after missing values have quietly removed part of the sample.</li>
</ul>
</div>
<div class="swirl">
<p><strong>In the seminar.</strong> <code>swirl</code> lesson <strong>06 Hypothesis Testing</strong>. Variation, drawing repeated samples and watching the sampling distribution appear, the standard error, and confidence intervals. Around 30 minutes.</p>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-logical-models.html" class="pagination-link" aria-label="Thinking logically and visually about data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Thinking logically and visually about data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./07-categorical-data.html" class="pagination-link" aria-label="Analysing categorical data">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analysing categorical data</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>