<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Factor analysis – Quantitative Methods I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-regression-basics.html" rel="next">
<link href="./09-correlation.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7202036dd3638cbfcbeb4151d116aa42.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./10-factor-analysis.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factor analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Quantitative Methods I</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-r-and-rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Getting started with R and RStudio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-data-management-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data management I</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-data-management-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data and data management II</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-logical-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Thinking logically and visually about data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data visualisation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-hypothesis-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The logic of hypothesis testing</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-categorical-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Analysing categorical data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-comparing-means.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Comparing means</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-correlation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-factor-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factor analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-regression-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression: the basic model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-regression-presentation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Regression: presenting results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-regression-dummies.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Regression: dummy variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-regression-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Regression: interactions and non-linear associations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-logistic-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Logistic regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link active" data-scroll-target="#the-problem"><span class="header-section-number">10.1</span> The problem</a></li>
  <li><a href="#look-at-the-correlations-first" id="toc-look-at-the-correlations-first" class="nav-link" data-scroll-target="#look-at-the-correlations-first"><span class="header-section-number">10.2</span> Look at the correlations first</a></li>
  <li><a href="#what-a-factor-is" id="toc-what-a-factor-is" class="nav-link" data-scroll-target="#what-a-factor-is"><span class="header-section-number">10.3</span> What a factor is</a></li>
  <li><a href="#is-it-worth-doing" id="toc-is-it-worth-doing" class="nav-link" data-scroll-target="#is-it-worth-doing"><span class="header-section-number">10.4</span> Is it worth doing?</a></li>
  <li><a href="#how-many-factors" id="toc-how-many-factors" class="nav-link" data-scroll-target="#how-many-factors"><span class="header-section-number">10.5</span> How many factors?</a></li>
  <li><a href="#one-factor" id="toc-one-factor" class="nav-link" data-scroll-target="#one-factor"><span class="header-section-number">10.6</span> One factor</a>
  <ul class="collapse">
  <li><a href="#the-item-that-does-not-belong" id="toc-the-item-that-does-not-belong" class="nav-link" data-scroll-target="#the-item-that-does-not-belong"><span class="header-section-number">10.6.1</span> The item that does not belong</a></li>
  </ul></li>
  <li><a href="#reliability" id="toc-reliability" class="nav-link" data-scroll-target="#reliability"><span class="header-section-number">10.7</span> Reliability</a></li>
  <li><a href="#making-a-variable" id="toc-making-a-variable" class="nav-link" data-scroll-target="#making-a-variable"><span class="header-section-number">10.8</span> Making a variable</a></li>
  <li><a href="#when-there-is-more-than-one-dimension" id="toc-when-there-is-more-than-one-dimension" class="nav-link" data-scroll-target="#when-there-is-more-than-one-dimension"><span class="header-section-number">10.9</span> When there is more than one dimension</a>
  <ul class="collapse">
  <li><a href="#rotation" id="toc-rotation" class="nav-link" data-scroll-target="#rotation"><span class="header-section-number">10.9.1</span> Rotation</a></li>
  <li><a href="#one-factor-or-two" id="toc-one-factor-or-two" class="nav-link" data-scroll-target="#one-factor-or-two"><span class="header-section-number">10.9.2</span> One factor or two?</a></li>
  </ul></li>
  <li><a href="#what-it-assumes" id="toc-what-it-assumes" class="nav-link" data-scroll-target="#what-it-assumes"><span class="header-section-number">10.10</span> What it assumes</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Factor analysis</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Last week ended with an 8×8 correlation matrix that had an obvious structure in it. This week is about what to do with a structure like that.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>swe <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"data/swe.rds"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>psych</code> is the standard R package for this. Install it once with <code>install.packages("psych")</code>.</p>
<section id="the-problem" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="the-problem"><span class="header-section-number">10.1</span> The problem</h2>
<p>The survey asked how much respondents trust seven institutions: parliament, the government, the judiciary, scientists, political parties, traditional media and social media. Each is a four-point scale, and we reversed them all so that a larger number means more trust.</p>
<p>That gives seven variables. But do we have seven <em>things</em>?</p>
<p>Almost certainly not. Somebody who trusts parliament probably trusts the government too. If most of what those seven questions measure is one underlying disposition — call it trust in institutions — then treating them as seven separate variables is both wasteful and misleading: put all seven into a regression and they will fight each other for the same explanatory work.</p>
<p><strong>Factor analysis</strong> asks whether a set of measured variables can be accounted for by a smaller number of unobserved ones.</p>
</section>
<section id="look-at-the-correlations-first" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="look-at-the-correlations-first"><span class="header-section-number">10.2</span> Look at the correlations first</h2>
<p>The same rule as always.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>trust_items <span class="ot">&lt;-</span> swe <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(tr_parl, tr_govt, tr_court, tr_sci, tr_party, tr_media, tr_socmed)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(trust_items) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Parliament"</span>, <span class="st">"Government"</span>, <span class="st">"Judiciary"</span>, <span class="st">"Scientists"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Parties"</span>, <span class="st">"Media"</span>, <span class="st">"Social media"</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">cor</span>(trust_items, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>), <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##              Parliament Government Judiciary Scientists Parties Media
## Parliament         1.00       0.72      0.55       0.30    0.51  0.40
## Government         0.72       1.00      0.53       0.32    0.53  0.38
## Judiciary          0.55       0.53      1.00       0.38    0.37  0.40
## Scientists         0.30       0.32      0.38       1.00    0.23  0.35
## Parties            0.51       0.53      0.37       0.23    1.00  0.35
## Media              0.40       0.38      0.40       0.35    0.35  1.00
## Social media       0.06       0.10      0.04       0.05    0.23  0.17
##              Social media
## Parliament           0.06
## Government           0.10
## Judiciary            0.04
## Scientists           0.05
## Parties              0.23
## Media                0.17
## Social media         1.00</code></pre>
</div>
</div>
<p>Nearly everything correlates positively with nearly everything, which is what a single common dimension looks like. Parliament and government are at 0.72.</p>
<p>One column stands out. Social media correlates with the rest at around 0.1 to 0.2 — much weaker than anything else in the table. Hold that thought.</p>
</section>
<section id="what-a-factor-is" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="what-a-factor-is"><span class="header-section-number">10.3</span> What a factor is</h2>
<p>The idea is that the correlations between the measured variables are produced by something they have in common.</p>
<p>Imagine a disposition — a general willingness to trust institutions — that varies between people. Someone high on it answers all seven questions a bit more positively. Someone low on it answers them all a bit more negatively. That common influence is what makes the answers correlate.</p>
<p>The unobserved disposition is the <strong>factor</strong>. Factor analysis works backwards from the correlations to estimate it.</p>
<p>Two quantities describe the result.</p>
<p>A <strong>loading</strong> is the correlation between a measured variable and the factor. It says how much that item reflects the underlying thing. Loadings run from −1 to +1, and by convention anything below about 0.3 is treated as not really loading at all.</p>
<p><strong>Variance explained</strong> is how much of the total variation in the items the factor accounts for.</p>
<blockquote class="blockquote">
<p><strong>Factor analysis is not causal discovery.</strong> It finds that some variables move together and summarises that. Whether the common thing is a real psychological disposition, an artefact of how the questions were worded, or a tendency to agree with anything, the arithmetic cannot tell you. That judgement is yours.</p>
</blockquote>
</section>
<section id="is-it-worth-doing" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="is-it-worth-doing"><span class="header-section-number">10.4</span> Is it worth doing?</h2>
<p>Two standard checks, both quick.</p>
<p><strong>Bartlett’s test</strong>, run by <code>cortest.bartlett()</code>, asks whether the correlation matrix differs from one with no correlations at all. If it does not, there is nothing to factor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cortest.bartlett</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(trust_items, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">n =</span> <span class="fu">sum</span>(<span class="fu">complete.cases</span>(trust_items))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## $chisq
## [1] 5193.501
## 
## $p.value
## [1] 0
## 
## $df
## [1] 21</code></pre>
</div>
</div>
<p><code>n</code> has to be supplied because the function is given a correlation matrix rather than the raw data, and a correlation matrix does not know how many people it came from.</p>
<p>The p-value is essentially zero, so the variables are correlated. With this much data that test almost always passes, and it is a floor rather than a recommendation.</p>
<p><strong>The KMO measure</strong> is more useful. It asks how much of the correlation between variables is shared rather than specific to pairs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">KMO</span>(trust_items)<span class="sc">$</span>MSA</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.8220836</code></pre>
</div>
</div>
<p><code>MSA</code> stands for measure of sampling adequacy. Above 0.8 is good, above 0.6 acceptable, below 0.5 means do not bother. 0.82 is fine.</p>
<p><code>KMO()</code> also reports a value per item, which is worth a look when one item is suspect:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">KMO</span>(trust_items)<span class="sc">$</span>MSAi, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##   Parliament   Government    Judiciary   Scientists      Parties        Media 
##         0.78         0.79         0.87         0.85         0.86         0.87 
## Social media 
##         0.60</code></pre>
</div>
</div>
<p>Social media again, at the bottom.</p>
</section>
<section id="how-many-factors" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="how-many-factors"><span class="header-section-number">10.5</span> How many factors?</h2>
<p>The awkward question, and the honest answer is that the standard criteria disagree with each other.</p>
<p>An <strong>eigenvalue</strong> measures how much variance a potential factor accounts for, in units where each individual item contributes 1. <code>eigen()</code> computes them from a correlation matrix, and the ones we want are in the <code>$values</code> part of what it returns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>trust_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(trust_items, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>eigen_values <span class="ot">&lt;-</span> <span class="fu">eigen</span>(trust_cor)<span class="sc">$</span>values</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(eigen_values, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 3.181 1.048 0.875 0.615 0.550 0.456 0.274</code></pre>
</div>
</div>
<p>The first is 3.18 — worth more than three items on its own. The second is 1.05, and everything after that is below 1.</p>
<p>Three ways to read that.</p>
<p><strong>The Kaiser criterion</strong>: keep factors with an eigenvalue above 1, on the logic that a factor should at least explain more than one item does. That gives 2 here. It is the crudest rule and it tends to keep too many.</p>
<p><strong>The scree plot</strong>: plot the eigenvalues in order and look for the elbow. <code>seq_along()</code> below makes the sequence 1, 2, 3, … as long as the vector it is given, which numbers the factors; <code>geom_hline()</code> marks the value 1 with <code>yintercept</code>, and <code>linetype = "dashed"</code> makes it a dashed line so that it reads as a reference rather than as data.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>scree_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">factor =</span> <span class="fu">seq_along</span>(eigen_values),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">eigenvalue =</span> eigen_values</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(scree_data, <span class="fu">aes</span>(<span class="at">x =</span> factor, <span class="at">y =</span> eigenvalue)) <span class="sc">+</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">+</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Factor"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Eigenvalue"</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-scree" class="quarto-float quarto-figure quarto-figure-center anchored" width="1050">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="10-factor-analysis_files/figure-html/fig-scree-1.png" id="fig-scree" class="img-fluid figure-img" width="1050">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-scree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1
</figcaption>
</figure>
</div>
</div>
</div>
<p>The drop from the first to the second is large, and after the second the line is nearly flat. The elbow is at two, which suggests keeping one — the factors <em>before</em> the elbow.</p>
<p><strong>Parallel analysis</strong>, run by <code>fa.parallel()</code>, is the best of the three. It generates random data of the same size and shape, factors that, and keeps only the factors that do better than random noise would.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>parallel <span class="ot">&lt;-</span> <span class="fu">fa.parallel</span>(trust_items, <span class="at">fa =</span> <span class="st">"fa"</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>parallel<span class="sc">$</span>nfact</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 3</code></pre>
</div>
</div>
<p>3 factors by that criterion.</p>
<p>So: Kaiser says 2, the scree plot suggests one, parallel analysis says 3. This is normal.</p>
<blockquote class="blockquote">
<p><strong>The criteria are advice, not answers.</strong> The real test is whether a solution is <em>interpretable</em> — whether the groups of items that hang together correspond to something you can name and defend. A statistically defensible solution you cannot explain is worse than a simpler one you can.</p>
</blockquote>
</section>
<section id="one-factor" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="one-factor"><span class="header-section-number">10.6</span> One factor</h2>
<p>Start simple, with one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>one_factor <span class="ot">&lt;-</span> <span class="fu">fa</span>(trust_items, <span class="at">nfactors =</span> <span class="dv">1</span>, <span class="at">fm =</span> <span class="st">"ml"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>one_factor<span class="sc">$</span>loadings</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Loadings:
##              ML1  
## Parliament   0.839
## Government   0.836
## Judiciary    0.657
## Scientists   0.412
## Parties      0.616
## Media        0.507
## Social media 0.131
## 
##                  ML1
## SS loadings    2.659
## Proportion Var 0.380</code></pre>
</div>
</div>
<p><code>fa()</code> is the workhorse. <code>nfactors</code> is how many to extract, and <code>fm = "ml"</code> is the estimation method — maximum likelihood, which is a reasonable default and gives you a significance test if you want one.</p>
<p>Read the loadings. Parliament (0.84) and government (0.84) load strongly: they are the clearest expressions of the underlying disposition. Judiciary and parties are solid. Scientists and media are weaker but real.</p>
<p>And social media, at 0.13, does not load at all.</p>
<p><code>Proportion Var</code> says the factor accounts for 38.0% of the total variance in the seven items.</p>
<section id="the-item-that-does-not-belong" class="level3" data-number="10.6.1">
<h3 data-number="10.6.1" class="anchored" data-anchor-id="the-item-that-does-not-belong"><span class="header-section-number">10.6.1</span> The item that does not belong</h3>
<p>A loading of 0.13 is a finding, not a nuisance. <strong>Trust in social media is not part of the same disposition as trust in institutions.</strong> On reflection that is obvious: social media is not an institution people are asked to have confidence in, and the question is probably measuring something closer to media habits.</p>
<p>Drop it and refit.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>trust_six <span class="ot">&lt;-</span> trust_items <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span><span class="st">`</span><span class="at">Social media</span><span class="st">`</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>six_factor <span class="ot">&lt;-</span> <span class="fu">fa</span>(trust_six, <span class="at">nfactors =</span> <span class="dv">1</span>, <span class="at">fm =</span> <span class="st">"ml"</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>six_factor<span class="sc">$</span>loadings</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Loadings:
##            ML1  
## Parliament 0.841
## Government 0.836
## Judiciary  0.658
## Scientists 0.412
## Parties    0.612
## Media      0.505
## 
##                  ML1
## SS loadings    2.639
## Proportion Var 0.440</code></pre>
</div>
</div>
<p>Backticks around <code>`Social media`</code> are needed because the name contains a space. This is why short names without spaces are worth the trouble.</p>
<p>Every item now loads above 0.4, and the variance explained rises to 44.0%.</p>
</section>
</section>
<section id="reliability" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="reliability"><span class="header-section-number">10.7</span> Reliability</h2>
<p>A related question: if these six items are meant to measure one thing, how consistently do they do it?</p>
<p><strong>Cronbach’s alpha</strong> is the standard measure. Roughly, it is how much the items agree with each other, on a scale where 1 is perfect.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>alpha_result <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(trust_six)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>alpha_result<span class="sc">$</span>total<span class="sc">$</span>raw_alpha</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.8127142</code></pre>
</div>
</div>
<p><code>psych::alpha()</code> is written out with its package name because several packages define a function called <code>alpha</code>, and whichever you loaded last wins.</p>
<p>0.813. The rough conventions are 0.7 acceptable, 0.8 good, 0.9 excellent — though above about 0.95 the items are probably redundant rather than reliable.</p>
<p>With all seven items, including social media, alpha was 0.780. Dropping the item that did not fit made the scale more reliable, not less.</p>
<blockquote class="blockquote">
<p>Alpha rises automatically as you add items, so a long scale can post a respectable alpha while measuring several different things. It is a check on a <em>one-dimensional</em> scale, which is why it comes after the factor analysis rather than instead of it.</p>
</blockquote>
</section>
<section id="making-a-variable" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="making-a-variable"><span class="header-section-number">10.8</span> Making a variable</h2>
<p>The practical payoff. Instead of six trust variables, we want one.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>swe<span class="sc">$</span>trust <span class="ot">&lt;-</span> six_factor<span class="sc">$</span>scores[, <span class="dv">1</span>]</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(swe<span class="sc">$</span>trust)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##      Min.   1st Qu.    Median      Mean   3rd Qu.      Max.       NAs 
## -3.021686 -0.460606  0.078510  0.009536  0.420305  1.929368       297</code></pre>
</div>
</div>
<p><code>scores</code> holds one <strong>factor score</strong> per respondent — an estimate of where each person sits on the underlying dimension. It comes out standardised, so a mean of about 0 and a standard deviation of about 1. Negative means less trusting than average.</p>
<blockquote class="blockquote">
<p><strong>Check the alignment.</strong> <code>fa()</code> returns as many rows as you gave it, with <code>NA</code> where a respondent was missing on any item. That means <code>swe$trust &lt;- six_factor$scores[, 1]</code> is correct. What is <em>not</em> correct is trying to be clever and assigning only into the complete rows — the lengths then do not match, R recycles, and everybody gets somebody else’s score.</p>
<p>The reason to be careful is that the broken version does not look broken. Writing this chapter, a misaligned version of exactly this variable produced differences between parties of a few hundredths of a point, which reads as a perfectly plausible finding of “no real differences”. Always check a new variable against something you already know.</p>
</blockquote>
<p>So check it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>swe <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(vote)) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(vote) <span class="sc">|&gt;</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean_trust =</span> <span class="fu">round</span>(<span class="fu">mean</span>(trust, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="dv">2</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## # A tibble: 8 × 3
##   vote      n mean_trust
##   &lt;fct&gt; &lt;int&gt;      &lt;dbl&gt;
## 1 V       138       0.01
## 2 MP      150       0.42
## 3 S       820       0.26
## 4 C       172       0.32
## 5 L       145       0.18
## 6 KD      133      -0.01
## 7 M       440       0.05
## 8 SD      336      -0.49</code></pre>
</div>
</div>
<p>Sweden Democrat voters are by some distance the least trusting, at -0.49. Green, Centre and Social Democrat voters are the most trusting. That is a recognisable pattern, and it did not go into the factor analysis — vote choice was never in the model.</p>
<p>A second check, against variables that should be related:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(swe<span class="sc">$</span>trust, swe<span class="sc">$</span>satdem, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.5279259</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(swe<span class="sc">$</span>trust, swe<span class="sc">$</span>demlevel, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 0.5489028</code></pre>
</div>
</div>
<p>Strongly correlated with satisfaction with democracy and with how democratic people think Sweden is, as it should be — but nowhere near 1, so it is not simply the same variable again. (Satisfaction with democracy has only four categories, so a Pearson correlation is being stretched here; as a rough check on whether a new variable behaves sensibly, that is a reasonable use of it.)</p>
<p>From here <code>trust</code> is an ordinary continuous variable. It goes into a regression in session 11 like any other.</p>
</section>
<section id="when-there-is-more-than-one-dimension" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="when-there-is-more-than-one-dimension"><span class="header-section-number">10.9</span> When there is more than one dimension</h2>
<p>So far we have asked the six items to be one thing, and they were willing. But “willing” is not the same as “best described that way”.</p>
<p>The criteria are split again. Look at the eigenvalues of the six-item set, and at what parallel analysis makes of them.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>parallel_six <span class="ot">&lt;-</span> <span class="fu">fa.parallel</span>(trust_six, <span class="at">fa =</span> <span class="st">"fa"</span>, <span class="at">plot =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>six_cor <span class="ot">&lt;-</span> <span class="fu">cor</span>(trust_six, <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>six_eigen <span class="ot">&lt;-</span> <span class="fu">eigen</span>(six_cor)<span class="sc">$</span>values</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(six_eigen, <span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 3.15 0.88 0.65 0.59 0.46 0.28</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>parallel_six<span class="sc">$</span>nfact</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## [1] 2</code></pre>
</div>
</div>
<p>The Kaiser rule says one, since the second eigenvalue is 0.88 and so below the threshold. Parallel analysis says 2.</p>
<p>There is also a reason to look beyond the criteria. Research on political trust distinguishes trust in the institutions of <em>party politics</em> — parliament, government, parties — from trust in institutions that hold authority without standing for election. If that distinction is present in these answers, one factor would be hiding it.</p>
<p>So try two, and see whether the split falls where theory says it should.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>two_factors <span class="ot">&lt;-</span> <span class="fu">fa</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  trust_six,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nfactors =</span> <span class="dv">2</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rotate =</span> <span class="st">"oblimin"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fm =</span> <span class="st">"ml"</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(two_factors<span class="sc">$</span>loadings, <span class="at">cutoff =</span> <span class="fl">0.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>## 
## Loadings:
##            ML1    ML2   
## Parliament  0.847       
## Government  0.865       
## Judiciary   0.384  0.377
## Scientists         0.657
## Parties     0.574       
## Media              0.494
## 
##                  ML1   ML2
## SS loadings    1.969 0.821
## Proportion Var 0.328 0.137
## Cumulative Var 0.328 0.465</code></pre>
</div>
</div>
<p><code>cutoff = 0.3</code> hides the small loadings so that the pattern is visible. <code>rotate = "oblimin"</code> needs explaining, and does so below.</p>
<p>The split is not arbitrary. The first factor is <strong>parliament, government and parties</strong> — the institutions of party politics, the ones you vote for and against. The second is <strong>scientists and the media</strong> — institutions with authority but no electoral role.</p>
<p>That distinction is a real one in the research on political trust, and it did not have to appear here. It is the sort of result that makes a two-factor solution worth taking seriously.</p>
<p>The judiciary is the interesting case: 0.38 on one factor and 0.38 on the other. An item that loads about equally on two factors is called a <strong>cross-loading</strong>, and it is telling you something — the courts are political and non-political at once, which is more or less what a constitutional court is for.</p>
<section id="rotation" class="level3" data-number="10.9.1">
<h3 data-number="10.9.1" class="anchored" data-anchor-id="rotation"><span class="header-section-number">10.9.1</span> Rotation</h3>
<p>When you extract more than one factor, the solution is not unique. Several different sets of axes describe the same data equally well, in the way that a set of points can be described from more than one angle. <strong>Rotation</strong> picks the angle that is easiest to interpret, by trying to make each item load strongly on one factor and weakly on the rest.</p>
<p>The choice that matters is whether the factors are allowed to correlate.</p>
<ul>
<li><strong>Orthogonal</strong> rotations, of which <code>varimax</code> is the common one, force the factors to be uncorrelated.</li>
<li><strong>Oblique</strong> rotations, such as <code>oblimin</code>, allow them to correlate.</li>
</ul>
<p>Look at what our factors actually do.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(two_factors<span class="sc">$</span>Phi, <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##       ML1   ML2
## ML1 1.000 0.661
## ML2 0.661 1.000</code></pre>
</div>
</div>
<p><code>Phi</code> holds the correlations between the factors: 0.66. People who trust parliament also tend to trust scientists. That is not a nuisance, it is the finding — there is a general trusting disposition, and two more specific ones on top of it.</p>
<p>Now force them apart and see what it costs.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>orthogonal <span class="ot">&lt;-</span> <span class="fu">fa</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  trust_six,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nfactors =</span> <span class="dv">2</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">rotate =</span> <span class="st">"varimax"</span>,</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">fm =</span> <span class="st">"ml"</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">unclass</span>(orthogonal<span class="sc">$</span>loadings), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>##              ML1   ML2
## Parliament 0.793 0.303
## Government 0.801 0.287
## Judiciary  0.491 0.490
## Scientists 0.169 0.591
## Parties    0.555 0.253
## Media      0.307 0.514</code></pre>
</div>
</div>
<p><code>unclass()</code> strips the special printing that <code>psych</code> attaches to a loadings table, so that every number shows rather than only the large ones. And the clean structure has gone. Under <code>varimax</code> the judiciary loads 0.49 and 0.49, parliament picks up a loading of 0.30 on the second factor, and almost everything loads moderately on both. Because the rotation is not allowed to put the correlation between the factors, it has to put it into the loadings instead — and the result describes the data less well while looking more complicated.</p>
<blockquote class="blockquote">
<p><strong>For social science, oblique is nearly always the right default.</strong> Real underlying dimensions are seldom independent of each other, and <code>varimax</code> produces a tidy-looking solution by asserting something about the world that is usually false. If the factors genuinely are uncorrelated, an oblique rotation will report a correlation near zero and you have lost nothing.</p>
</blockquote>
</section>
<section id="one-factor-or-two" class="level3" data-number="10.9.2">
<h3 data-number="10.9.2" class="anchored" data-anchor-id="one-factor-or-two"><span class="header-section-number">10.9.2</span> One factor or two?</h3>
<p>Both solutions are defensible fits to the same six items.</p>
<p>The one-factor solution says there is a general disposition to trust institutions, and it explains 44.0% of the variance. The two-factor solution says that disposition has two related parts, political and non-political, correlated at 0.66.</p>
<p>Which you take depends on what you are going to do with it. If you want one variable for a regression, take one factor — the two are correlated at 0.66 anyway, and separating them buys little. If your argument is specifically about the difference between trust in politicians and trust in expertise, take two, and say why.</p>
<div class="discussion">
<p><strong>A question.</strong> The criteria gave three different answers about the number of factors, and both solutions are interpretable.</p>
<p>Suppose you fitted one factor, and a reviewer says you should have fitted two. What evidence could you offer in reply — and is “parallel analysis suggested three” a point in your favour or against you?</p>
</div>
</section>
</section>
<section id="what-it-assumes" class="level2" data-number="10.10">
<h2 data-number="10.10" class="anchored" data-anchor-id="what-it-assumes"><span class="header-section-number">10.10</span> What it assumes</h2>
<p><strong>Continuous items, or close enough.</strong> Our trust items are four-point scales, which is below the five-category rule from session 2. This is extremely common practice and it is a real compromise; <code>psych</code> offers <code>cor = "poly"</code> to treat items as ordinal, which is the more defensible route for short scales.</p>
<p><strong>Enough cases.</strong> The usual advice is at least 10 per item, and more for weak loadings. With 2548 complete cases on six items, we are not short.</p>
<p><strong>Linear relationships</strong>, since the whole thing is built on a correlation matrix — with everything that implies about what correlations miss.</p>
<div class="reporting">
<p><strong>How to write it up.</strong></p>
<blockquote class="blockquote">
<p>The six institutional trust items were subjected to maximum likelihood factor analysis. Sampling adequacy was good (KMO = 0.83) and Bartlett’s test was significant (<em>p</em> &lt; .001). A single factor was retained, accounting for 44.0% of the variance, with loadings from 0.41 (scientists) to 0.84 (parliament). Internal consistency was good (α = 0.81). A seventh item, trust in social media, loaded at 0.13 and was excluded. Factor scores were saved for use in the models below.</p>
</blockquote>
<p>Say which items, which method, how many factors and why, the loadings, the variance explained, and what you did with the result. Mistakes to avoid:</p>
<ul>
<li><strong>Not saying which rotation you used</strong>, or using an orthogonal one without justifying it.</li>
<li><strong>Reporting the number of factors without the reasoning.</strong> The criteria disagree; say which you followed.</li>
<li><strong>Hiding a dropped item.</strong> Report it and say why it went.</li>
<li><strong>Reporting alpha instead of a factor analysis.</strong> Alpha assumes one dimension; it does not test for it.</li>
<li><strong>Naming a factor after what you hoped to find</strong> rather than after the items that actually load on it.</li>
<li><strong>Treating factor scores as if they were measured without error.</strong> They are estimates, and the uncertainty does not carry into the next model.</li>
<li><strong>Running the analysis on items with different scale directions.</strong> Reverse them first, or the factor will split into “agree” and “disagree” and mean nothing.</li>
</ul>
</div>
<div class="swirl">
<p><strong>In the seminar.</strong> <code>swirl</code> lesson 10, <em>Factor Analysis</em>. Checking whether a set of items hangs together, deciding how many factors, reading loadings, reliability, and saving factor scores. Around 30 minutes.</p>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-correlation.html" class="pagination-link" aria-label="Correlation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Correlation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-regression-basics.html" class="pagination-link" aria-label="Regression: the basic model">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Regression: the basic model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>